GKernelCI/GBuildbot

master.cfg
Gentoo Kernel CI as been public released, so we are updating the url
=> updated the Gentoo kernel CI buildbot url

master.cfg
Getting Github token from BUILDBOT_STATUS_TOKEN os enviroment variable
fixing buildbot url link
=> add github token from env and fix buildbot url

master.cfg
fixed kernel check factory git checkout url to gentoo/linux-patches
function filterFiles get the changed files under
sys-kernel/gentoo-sources and is adding it to the python script as
argument.
=> add stabilization factory example

files/check-kernelpage.py
Currently, most of the scripts are running correctly with both python3 and python2, except this one. This is due to incompatibility issues on the urlllib, tarfile and lzma.
=> check-kernelpage.py: Add compatibility for python2

master.cfg
This adds branch 4.16 for testing kernel builds and boot. This is based onto my branch for ARM. So you should first merge the PR for ARM (#53 ), then merge this one.
Regards,
Romain
=> Monitor branch 4.16 for kernel builders

files/qemu_check.py
Checking for qemu test image was inconsistent between ARM and amd64
configurations, leading to some incorrect assumption that the ARM
image permanently existed.
Expanded the logic from amd64 to handle downloading an ARM qemu test
image, although there is presently no URI set up for this in code yet.
Added a secondary test to check whether image correctly downloaded,
and fail cleanly if not.
=> Fix checking of qemu test image existence prior to downloading

files/check-kernelpage.py
Kernel version is a simple string, but gets 'exploded' in scripts that follow,
leading to some completely unviable commands trying to be run!
=> Make kernel version into a list, to prevent expansion after 'shelve'ing

master.cfg
The password is hidden in the mail_password file.
This is just a simple hack and need better code.
=> Add smtp email informations

master.cfg
I have removed some of the older kernel branches as I'm not sure there is any merit in keeping configs for them, if there are genuinely no updates likely.
However, if there is some reason to keep them around, happy to revert this particular prune!
=> Add 4.20 kernel branch, remove old/unused

files/clean.sh, files/qemu_check.py, master.cfg
This seems to be a fairly robust answer to the issue of multiple builds wanting to concurrently access the qemu test image for boot testing.
I think the only thing missing from this PR is cleanup of the resulting snapshots/'clones' but as these should be Copy-on-Write, they should actually be small in size anyway.
Deployed, tested & running successfully on 'vmz-ci-test'.
=>  Improve qemu test image handling

files/patch-kernel.sh
Because we are trying to build with different
architecture using oldconfig and reusing .config
is sometime not going to work.
=> Use defcofing instead of oldconfig

files/patch-kernel.sh
Not 100% sure on this, but pretty sure mrproper or distclean will
clean .config. Re-order 'make mrproper' and the copy command
so that mrproper cannot wipe copied config!
=> Fix 'make oldconfig' so that existing config isn't wiped

master.cfg
=> Set limit on concurrent jobs on worker to 4

files/check-kernelpage.py
Presently, there is some logic in ebuilds which selectively
applies patches depending on some environment parameters.
Until we have a mechanism in kernelCI to replicate this,
disable applying experimental patches for now.
Experimental patches may/may not be fully supported, but
these can be monitored separately from the main genpatches
set for the time being.
At some stage in the future, when we have finer-grained
application of patches in the CI system, these can probably
be added back in to the mix.
=> Remove experimental patches from patch list

master.cfg
Buildbot 2.x
Signed-off-by: Michael Everitt <gentoo@veremit.xyz>
=> Send IRC messages as notices, not channel messages

factory/images_builder.py
Build script will need to know build_name, build_number and source tree
path.
=> Add more arguments to build script

factory/images_builder.py
Usefull files from build are copied in FILESERVER, so there are no
reason to keep the rest of the builds.
So let's remove it at the end.
=> clean build after tests

master.cfg
buildbot complain on each startup to configure buildbotNetUsageData.
So let's set it to None to silent it.
=> Configure buildbotNetUsageData

builders.py
=> gentoo_sources: fix typo in builders

factory/images_builder.py
=> factory: fix unexpected keyword argument ['logenviron']

config_stabilization.yaml, settings.py
=> config_stabilization: remove not for stable keywords

config_stabilization.yaml
=> stabilization: remove ppc64le as currently not working
