master.cfg
For gentoo repository added a function that work only if the push or
pull request change is for sys-kernel/gentoo-sources* packages.
Linux-patches work for change in branches or if a branch+"_stabilize" is
added.
=> Adding puller for github and git linux-patches and gentoo repository.

.travis.yml
added treq as pip requirements
removed --use-mirrors from pip options
added master/password example
removed pip2.6 becasue not needed
=> fixed travis configuration

.travis.yml
added worker config file example
=> changed echo with printf for get newline char

master.cfg
take workers information from workers.cfg configuration file
=> Adding multiworker script

master.cfg
=> Add MailNotifier for buildbot results (initial testing)

files/build-kernel.sh, files/patch-kernel.sh, files/qemu_check.py, master.cfg
=> Adding architecture support for ARM

files/qemu_check.py, master.cfg
=> Fix problem sharing qcow image for multiple concurrent builds

master.cfg
Mostly white-space adjustments, to improve readability.
=> Tidy up a few more PEP8 issues

master.cfg
Signed-off-by: Michael Everitt <m.j.everitt@iee.org>
=> Added upstream branch 4.18 to checks

master.cfg
=> Add 4.19 branch to tracking, consolidate branch list code

master.cfg
Signed-off-by: Michael Everitt <m.j.everitt@iee.org>
=> Abort build if certain key steps fail

files/clean.py, files/clean.sh
=> Fix cleaning

files/clean.py
Signed-off-by: Michael Everitt <m.j.everitt@iee.org>
=> Overhaul clean.py, add some debugging info

files/clean.py
Also update shebang to specify python3, handle non-existant build files
Signed-off-by: Michael Everitt <m.j.everitt@iee.org>
=> Rework clean.py to use python file routines

.codeclimate.yml
=> Add code climate config to remove 'bandit' engine

.travis.yml
=> Update .travis.yml to python3.5 for buildbot-2.0

files/stabilize-packages.py
What a train-wreck that was!
This is the complete, fully signed-off, version. Finally.
=> Overhaul stabilize

files/clean.py
=> Fix incorrect package-cleanup script name

files/check-kernelpage.py
=> Fix patch download URLs to work with 5.x branch series

master.cfg
=> Abort build attempt if version-check or subsequent patching fails

master.cfg
=> Add linux-5.1 branch to upstream checks

master.cfg
=> Update www-plugin config syntax, add grid_view

files/patch-kernel.sh
=> Set 'patch-kernel' to abort on failure, so that we trap any undesirables

files/clean.py
=> Fixed incorrect path to ebuilds, causing cleans to be skipped

master.cfg
=> master.cfg: Rename IRC status bot per alicef's request

master.cfg
=> Add 5.2 branch and remove 5.0 from upstream tracking

master.cfg
- Update email address for Michael Everitt
- Move IRC reporter bot to #gentoo-kernelci channel (Freenode)
=> Config changes 20190729

master.cfg
See: https://gitlab.com/oxr463/buildbot_tyrian_theme
=> Use Tyrian theme for UI

master.cfg
=> Fix roles configuration variable

factory/images_builder.py
=> Add step for send job results to kcidb

factory/images_builder.py
=> Steps build and patch are now sending result to kcidb

factory/images_builder.py
=> Add discoverytime data for kcidb

builders.py, schedulers.py
This PR depends on https://github.com/GKernelCI/Ghelper/pull/24
=> Add arm64 as buildable architecture

builders.py, schedulers.py
=> Build arm ppc64 and sparc64 arch

schedulers.py
=> Add ForceScheduler for each build

builders.py, config.yaml, schedulers.py, settings.py
Add toolchain in builder_name.This PR need the Ghelper PR https://github.com/GKernelCI/Ghelper/pull/33 to be merged.
=> Toolchain in buildname

builders.py, config.yaml, master.cfg, schedulers.py, settings.py
This PR adds support for configuring workers in a yaml file.
This permits to add more than one worker.
It permits also to configure arch/toolchain to do per worker.
CAUTION: this need also the PR against GBuildbot-master
=> Workerlist

settings.py
Remove old non-stable kernel which are not in portage anymore.
Add 5.17 and 5.15.
=> Update kernel version list

settings.py
Add 5.4 and 5.18 kernel to test. (5.4 was removed by accident).
=> Add 5.4 and 5.18

schedulers.py
=> Add try scheduler for buildbot try command

config.yaml
TODO: add the toolchain doing gentoo-sources testing
=> Clean current toolchain on git release

schedulers.py
=> schedulers: Update exclusion list for packages that are not *-sources

settings.py
=> settings: update to kernel v6.0

factory/images_builder.py
=> images_builder: add date for stabilization step

factory/images_builder.py
=> factory/images_builder: get kernel packages name

settings.py
=> settings: drop kernel versions

schedulers.py
=> gentoo_sources: update name

builders.py, schedulers.py
=> other_sources: Add stabilization arch also to other_sources

builders.py, factory/images_builder.py
=> factory: add arch for stabilization

factory/images_builder.py
=> factory/stabilization: pass arch value also during building

factory/images_builder.py
=> factory/stabiliztion: test change name with interpolate

factory/images_builder.py
=> factory/stabilization: add package versions property

factory/images_builder.py
=> factory/stabilization: simplify package versions list

builders.py, factory/images_builder.py
Prepare eclass testing from having is own testing system
=> factory: rename factory functions and add eclass function

builders.py
=> builders: fix typo

config_stabilization.yaml
=> config_stabilization: type int to str

factory/images_builder.py
=> factory/linux-patches: remove source path as is get from the script

factory/images_builder.py
=> factory/linux-patches: fix build-kernel.sh script directory

factory/images_builder.py
=> factory/stabilization: check packages existence

schedulers.py
=> schedulers: update to ChangeFilter to v3.7.0

schedulers.py
Reverts GKernelCI/GBuildbot#177
=> Revert "schedulers: update to ChangeFilter to v3.7.0"

settings.py
closes https://github.com/GKernelCI/GBuildbot/issues/185
=> fix: adjust branches_list based on kernel.org support model
